apiVersion: v1
kind: ConfigMap
metadata:
  name: podset-logger-config
  namespace: podset-operator-group
data:
  podset-logger-config.yaml: |
    version: "0.0.1"
    label: "podset-logger"
    value: "2"
    forecast: "Salut Serge"
